baseURL = 'https://spine.io/'
languageCode = 'en-us'
title = 'Documentation preview'

[module]
  [[module.imports]]
    path = 'github.com/TeamDev-Ltd/site-commons'
  [[module.imports]]
    path = '../../_hugo-theme'

# Enables HTML rendering in markdown files.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
