name: Check Code Embedding

on:
  pull_request:

jobs:
  build-embedded-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: zulu

      - run: ./gradlew :buildAll

  check-embedded-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: zulu

      - name: Check Embedding
        run: ./gradlew :checkSamples
